### ISSUE TITLE
Test cases failing in AdminController and AnswerController

### ISSUE THREAD

**Issue by vioravis** [vioravis/Trello_quora#26]
Two test cases are failing

[ERROR] Failures: 
[ERROR]   AdminControllerTest.deleteNonExistingUser:47 Status expected:<404> but was:<403>
[ERROR]   QuestionControllerTest.editQuestionWithoutOwnership:87 JSON path "code" expected:<ATHR-003> but was:<ATHR-002>
[INFO]
[ERROR] Tests run: 19, Failures: 2, Errors: 0, Skipped: 0
[INFO]

**Comment by krishnapotla** [comment]
Rejected. before verifying the user, we have to verify the login session
