### ISSUE TITLE
Test cases failing in admin, answer and question controllers

### ISSUE THREAD

**Issue by vioravis** [vioravis/Trello_quora#27]
[ERROR] Failures: 
[ERROR]   AdminControllerTest.deleteNonExistingUser:47 Status expected:<404> but was:<403>
[ERROR]   AnswerControllerTest.createAnswerForNonExistingQuestion:47 Status expected:<404> but was:<403>
[ERROR]   AnswerControllerTest.editAnswerWithoutOwnership:80 JSON path "code" expected:<ATHR-003> but was:<ATHR-002>
[ERROR]   AnswerControllerTest.getAllAnswersToNonExistingQuestion:135 Status expected:<404> but was:<403>
[ERROR]   QuestionControllerTest.editQuestionWithoutOwnership:87 JSON path "code" expected:<ATHR-003> but was:<ATHR-002>
[INFO]
[ERROR] Tests run: 33, Failures: 5, Errors: 0, Skipped: 0
[INFO]

**Comment by krishnapotla** [comment]
Rejected. before verifying the user, we have to verify the login session
