### ISSUE TITLE
Questions deleted by non-creator or admin

### ISSUE THREAD

**Issue by vioravis** [vioravis/Trello_quora#28]
The following condition is not working:

Only the question owner or admin can delete the question. Therefore, if the user who is not the owner of the question or the role of the user is ‘nonadmin’ and tries to delete the question, throw 'AuthorizationFailedException' with the message code-'ATHR-003' and message -'Only the question owner or admin can delete the question'.

**Comment by krishnapotla** [comment]
Fixed
